#!/usr/bin/env bash
set -euo pipefail

# We expect 6 header args + 18 gesture args (+ optional 1 for custom commands)
# Total: 24 or 25 args (original was 24)
if (( $# < 24 || $# > 25 )); then
  echo "expected 24 or 25 settings, got $#" >&2
  exit 2
fi

enabled=$1
click_method=$2
tap_map=$3
capture_trigger=$4
capture_action=$5
screenshot_editor=$6

# Save custom commands arg (position 25) before shifting
custom_commands_raw=""
if (( $# == 25 )); then
  custom_commands_raw="${25}"
fi

shift 6

case "$enabled" in true|false) ;; *) exit 2 ;; esac
case "$click_method" in clickfinger|buttonareas) ;; *) exit 2 ;; esac
case "$tap_map" in lrm|lmr) ;; *) exit 2 ;; esac
case "$capture_trigger" in none|twofinger|threefinger|buttonarea) ;; *) exit 2 ;; esac
case "$capture_action" in screenshot|record) ;; *) exit 2 ;; esac
case "$screenshot_editor" in true|false) ;; *) exit 2 ;; esac

directions=(left right up down pinchin pinchout)
actions=(none workspace relative_workspace move resize special close fullscreen maximize float tile cursor_zoom scroll_move focus expose custom_command)

# Parse custom commands into an associative array
declare -A custom_cmd_map
if [[ -n $custom_commands_raw ]]; then
  while IFS='|' read -r key cmd; do
    [[ -n $key && -n $cmd ]] && custom_cmd_map[$key]=$cmd
  done <<< "$custom_commands_raw"
fi
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
output="$config_dir/gestures-generated.lua"
temporary="$output.tmp"

valid_action() {
  local candidate=$1 allowed
  for allowed in "${actions[@]}"; do
    [[ $candidate == "$allowed" ]] && return 0
  done
  return 1
}

gesture_line() {
  local fingers=$1 direction=$2 action=$3 short_direction workspace_target
  [[ $action == none ]] && return 0
  valid_action "$action" || return 2

  case "$action" in
    maximize)
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = "fullscreen", mode = "maximize" })\n' "$fingers" "$direction"
      ;;
    tile)
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = "float", mode = "tile" })\n' "$fingers" "$direction"
      ;;
    special)
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = "special", workspace_name = "special" })\n' "$fingers" "$direction"
      ;;
    cursor_zoom)
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = "cursor_zoom", zoom_level = 1, mode = "live" })\n' "$fingers" "$direction"
      ;;
    focus)
      case "$direction" in left) short_direction=l ;; right) short_direction=r ;; up) short_direction=u ;; down) short_direction=d ;; *) short_direction=l ;; esac
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = function() hl.dispatch(hl.dsp.focus({ direction = "%s" })) end })\n' "$fingers" "$direction" "$short_direction"
      ;;
    expose)
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = function() os.execute("omarchy-shell expose toggle") end })\n' "$fingers" "$direction"
      ;;
    custom_command)
      local cmd_key="${fingers}_${direction}"
      local cmd="${custom_cmd_map[$cmd_key]:-}"
      if [[ -n $cmd ]]; then
        # Use Lua long bracket syntax [=[...]=] to avoid escaping issues
        # Need to handle the case where cmd contains ]=]
        local lua_cmd
        if [[ $cmd == *']=]'* ]]; then
          lua_cmd="[==[${cmd}==]"
        else
          lua_cmd="[=[${cmd}]=]"
        fi
        printf 'hl.gesture({ fingers = %s, direction = "%s", action = function() os.execute(%s) end })\n' "$fingers" "$direction" "$lua_cmd"
      fi
      ;;
    relative_workspace)
      case "$direction" in
        right|down|pinchout) workspace_target='+1' ;;
        left|up|pinchin) workspace_target='-1' ;;
        *) workspace_target='+1' ;;
      esac
      case "$direction" in
        left|right) short_direction=x ;;
        *) short_direction=y ;;
      esac
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = relative_workspace_gesture("%s", "%s") })\n' "$fingers" "$direction" "$workspace_target" "$short_direction"
      ;;
    *)
      printf 'hl.gesture({ fingers = %s, direction = "%s", action = "%s" })\n' "$fingers" "$direction" "$action"
      ;;
  esac
}

clickfinger=false
[[ $click_method == clickfinger ]] && clickfinger=true

{
  printf '%s\n' '-- Generated by user.trackpad-gestures. Changes will be overwritten.'
  cat <<'LUA'
local function relative_workspace_gesture(target, axis)
  local distance = 0
  local triggered = false

  local function consume(event)
    if triggered then return end
    local delta = axis == "x" and event.delta.x or event.delta.y
    distance = distance + math.abs(delta)
    if distance >= 25 then
      triggered = true
      hl.dispatch(hl.dsp.focus({ workspace = target }))
    end
  end

  return {
    start = function(event)
      distance = 0
      triggered = false
      consume(event)
    end,
    update = consume,
    finish = function()
      distance = 0
      triggered = false
    end,
  }
end
LUA
  printf 'hl.config({ input = { touchpad = { clickfinger_behavior = %s, tap_button_map = "%s" } } })\n' "$clickfinger" "$tap_map"
  if [[ $capture_trigger != none ]]; then
    capture_button=273
    [[ $capture_trigger == threefinger ]] && capture_button=274

    if [[ $capture_action == record ]]; then
      capture_command='omarchy-capture-screenrecording --stop-recording || omarchy-menu toggle trigger.capture.screenrecord'
      capture_description='Trackpad screen recording'
    elif [[ $screenshot_editor == true ]]; then
      capture_command="$HOME/.config/omarchy/plugins/user.trackpad-gestures/screenshot-editor.sh"
      capture_description='Trackpad screenshot with editor'
    else
      capture_command='omarchy-capture-screenshot smart copy'
      capture_description='Trackpad screenshot'
    fi

    printf 'o.bind("mouse:%s", "%s", "%s", { mouse = true })\n' "$capture_button" "$capture_description" "$capture_command"
  fi
if [[ $enabled == true ]]; then
    configured=("$@")
    offset=0
    for fingers in 2 3 4; do
      left=${configured[$offset]}
      right=${configured[$((offset + 1))]}
      up=${configured[$((offset + 2))]}
      down=${configured[$((offset + 3))]}
      pinch_in=${configured[$((offset + 4))]}
      pinch_out=${configured[$((offset + 5))]}

      # Libinput reserves two-finger directional motion for page scrolling.
      # Never emit swipe gestures for two fingers, even if stale settings exist.
      if (( fingers == 2 )); then
        left=none
        right=none
        up=none
        down=none
      fi

      if [[ $left == "$right" && $left != none && $left != focus && $left != relative_workspace ]]; then
        gesture_line "$fingers" horizontal "$left"
      else
        gesture_line "$fingers" left "$left"
        gesture_line "$fingers" right "$right"
      fi

      if [[ $up == "$down" && $up != none && $up != focus && $up != relative_workspace ]]; then
        gesture_line "$fingers" vertical "$up"
      else
        gesture_line "$fingers" up "$up"
        gesture_line "$fingers" down "$down"
      fi

      if [[ $pinch_in == "$pinch_out" && $pinch_in != none && $pinch_in != focus && $pinch_in != relative_workspace ]]; then
        gesture_line "$fingers" pinch "$pinch_in"
      else
        gesture_line "$fingers" pinchin "$pinch_in"
        gesture_line "$fingers" pinchout "$pinch_out"
      fi

      offset=$((offset + 6))
    done
  fi
} > "$temporary"

mv "$temporary" "$output"
hyprctl reload >/dev/null
errors=$(hyprctl configerrors)
if [[ -n $errors ]]; then
  printf '%s\n' "$errors" >&2
  exit 1
fi
